# Generated by Django 4.1.2 on 2022-11-04 14:58

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name='Created at',
                    ),
                ),
                (
                    'modified_at',
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name='Modified at',
                    ),
                ),
                ('title', models.CharField(max_length=64, verbose_name='Name')),
                (
                    'slug',
                    models.CharField(
                        blank=True, max_length=256, unique=True, verbose_name='URL'
                    ),
                ),
                (
                    'min_ram',
                    models.PositiveIntegerField(verbose_name='Minimum RAM (MB)'),
                ),
                (
                    'min_disk_space',
                    models.PositiveIntegerField(verbose_name='Minimum Disk Space (MB)'),
                ),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GameSoftware',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name='Created at',
                    ),
                ),
                (
                    'modified_at',
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name='Modified at',
                    ),
                ),
                ('name', models.CharField(max_length=64, verbose_name='Software Name')),
                (
                    'name_suffix',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=64,
                        verbose_name='Software Name Suffix',
                    ),
                ),
                (
                    'default_port',
                    models.PositiveIntegerField(verbose_name='Default Port'),
                ),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='server.game',
                        verbose_name='Game',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Game Software',
                'verbose_name_plural': 'Game Software',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name='Created at',
                    ),
                ),
                (
                    'modified_at',
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name='Modified at',
                    ),
                ),
                ('ip', models.CharField(max_length=15, verbose_name='IP')),
                ('cores', models.PositiveIntegerField(verbose_name='Cores')),
                ('ram', models.PositiveIntegerField(verbose_name='RAM (MB)')),
                (
                    'disk_space',
                    models.PositiveIntegerField(verbose_name='Disk Space (GB)'),
                ),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameSoftwareVersion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name='Created at',
                    ),
                ),
                (
                    'modified_at',
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name='Modified at',
                    ),
                ),
                (
                    'version',
                    models.CharField(max_length=64, verbose_name='Software Version'),
                ),
                (
                    'version_suffix',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=64,
                        verbose_name='Software Version Suffix',
                    ),
                ),
                (
                    'software',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='server.gamesoftware',
                        verbose_name='Game Software',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Software Version',
                'verbose_name_plural': 'Software Versions',
            },
        ),
    ]
