# Generated by Django 4.1.2 on 2023-01-13 21:52

import datetime

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models

import server.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name='Created at',
                    ),
                ),
                (
                    'modified_at',
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name='Modified at',
                    ),
                ),
                ('title', models.CharField(max_length=64, verbose_name='Name')),
                (
                    'slug',
                    models.CharField(
                        blank=True, max_length=256, unique=True, verbose_name='URL'
                    ),
                ),
                (
                    'min_ram',
                    models.PositiveIntegerField(verbose_name='Minimum RAM (MB)'),
                ),
                (
                    'min_disk_space',
                    models.PositiveIntegerField(verbose_name='Minimum Disk Space (MB)'),
                ),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GameSoftware',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name='Created at',
                    ),
                ),
                (
                    'modified_at',
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name='Modified at',
                    ),
                ),
                ('name', models.CharField(max_length=64, verbose_name='Software Name')),
                (
                    'name_suffix',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=64,
                        verbose_name='Software Name Suffix',
                    ),
                ),
                (
                    'default_port',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(65535)],
                        verbose_name='Default Port',
                    ),
                ),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='server.game',
                        verbose_name='Game',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Game Software',
                'verbose_name_plural': 'Game Software',
            },
        ),
        migrations.CreateModel(
            name='GameSoftwareVersion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name='Created at',
                    ),
                ),
                (
                    'modified_at',
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name='Modified at',
                    ),
                ),
                (
                    'version',
                    models.CharField(max_length=64, verbose_name='Software Version'),
                ),
                (
                    'version_suffix',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=64,
                        verbose_name='Software Version Suffix',
                    ),
                ),
                (
                    'software',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='server.gamesoftware',
                        verbose_name='Game Software',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Software Version',
                'verbose_name_plural': 'Software Versions',
            },
        ),
        migrations.CreateModel(
            name='IPNet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name='Created at',
                    ),
                ),
                (
                    'modified_at',
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name='Modified at',
                    ),
                ),
                (
                    'ip_net',
                    models.CharField(
                        max_length=18,
                        validators=[server.validators.validate_cidr_notation],
                        verbose_name='CIDR Notation',
                    ),
                ),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'IPNet',
                'verbose_name_plural': 'IPNets',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name='Created at',
                    ),
                ),
                (
                    'modified_at',
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name='Modified at',
                    ),
                ),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('cores', models.PositiveIntegerField(verbose_name='Cores')),
                ('ram', models.PositiveIntegerField(verbose_name='RAM (MB)')),
                (
                    'disk_space',
                    models.PositiveIntegerField(verbose_name='Disk Space (GB)'),
                ),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGameServer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name='Created at',
                    ),
                ),
                (
                    'modified_at',
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name='Modified at',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name='Deleted at',
                    ),
                ),
                (
                    'server_name',
                    models.CharField(max_length=64, verbose_name='Gameserver Name'),
                ),
                (
                    'own_ip',
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name='Gameserver IP Address'
                    ),
                ),
                (
                    'port',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(65535)],
                        verbose_name='Gameserver Port',
                    ),
                ),
                ('ram', models.PositiveIntegerField(verbose_name='Gameserver RAM')),
                (
                    'disk_space',
                    models.PositiveIntegerField(verbose_name='Gameserver Disk Space'),
                ),
                ('cores', models.PositiveIntegerField(verbose_name='Gameserver Cores')),
                (
                    'available_until',
                    models.DateTimeField(verbose_name='Available Until'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('setup', 'is set up'),
                            ('enabled', 'enabled'),
                            ('delete', 'is being deleted'),
                            ('deleted', 'deleted'),
                            ('disabled', 'disabled'),
                            ('locked', 'locked'),
                        ],
                        default='setup',
                        max_length=64,
                        verbose_name='Gameserver Status',
                    ),
                ),
                (
                    'sql_password',
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=64, verbose_name='SQL Password')
                    ),
                ),
                (
                    'ftp_password',
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=64, verbose_name='FTP Password')
                    ),
                ),
                (
                    'extras',
                    models.JSONField(default=dict, verbose_name='Additional Data'),
                ),
                (
                    'node',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='server.node',
                        verbose_name='Selected Node',
                    ),
                ),
                (
                    'software_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='server.gamesoftwareversion',
                        verbose_name='Gameserver Software Version',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Gameserver',
                'verbose_name_plural': 'Gameservers',
            },
        ),
    ]
